### ISSUE TITLE
Super simple example / doc / desc

### ISSUE THREAD

**Issue by olaj** [gillbeits/gulp-fontello#4]
It would be awesome if someone could post just an example and simple description what this does. I know i can check the code and try to figure it out but it would be convenient if someone who has this up and running can post something :)

**Comment by simison** [comment]
Like this:
```
gulp.task('fontello', function(done) {
  return gulp.src('fontello-config.json')
    .pipe(fontello());
});
```

**Comment by olaj** [comment]
Thanks for the reply! Seems to work but i can't get it to update.

I had the same issue with some other fontello plugin, is the intended workflow to provide a config file and the be able to change my icons on the website and it will update the files in my project?

**Comment by simison** [comment]
@olaj FYI, now there's proper readme file in place.
